f=open("c:\\data\\funny.txt","w")
f.write("\n i love my daughters")
f.close()
f=open("c:\\data\\funny.txt","a")
f.write("\n they are everything to me")
f.close()
f=open("c:\\data\\funny.txt","r")
print(f.read())
f.close()
